source/content/hero.html, source/theme/landing-page-hero-section.html
This PR shows how we should separate page content from the page layout.
=> Content substitution

source/reference/stable/order-api/get-orders.md, source/reference/stable/order-api/get-shipments.md
[Task](https://centracommerce.atlassian.net/browse/CCT-357)
=> CCT-357 Updated documentation

package-lock.json, source/reference/stable/order-api/create-return.md
Added documentation about return + refund
=> Updated Order API documentation about Refund

user/themes/centra/centra.yaml, user/themes/centra/scss/_mixins.scss, user/themes/centra/scss/landing-page/_landing-page-basics-section.scss, user/themes/centra/scss/landing-page/_landing-page-certification-section.scss, user/themes/centra/scss/landing-page/_landing-page-footer.scss, user/themes/centra/scss/landing-page/_landing-page-get-started-section.scss, user/themes/centra/scss/landing-page/_landing-page-support-section.scss, user/themes/centra/scss/landing-page/_landing-page.scss, user/themes/centra/scss/search.scss, user/themes/centra/templates/homepage.html.twig, user/themes/centra/templates/macros/basic-articles.html.twig, user/themes/centra/templates/macros/docs-articles.html.twig, user/themes/centra/templates/partials/head.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-basics-section.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-certification-section.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-docs-section.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-footer.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-get-started-section.html.twig, user/themes/centra/templates/partials/landing-page/landing-page-support-section.html.twig
[JIRA](https://centracommerce.atlassian.net/browse/SHOWROOM-259)
=> fix: Add animation on scroll library

user/pages/01.guides/chapter.md, user/themes/centra/scss/_articles-listing.scss, user/themes/centra/scss/style.scss, user/themes/centra/templates/chapter.html.twig
Rename cover template to chapter, as it better describes it purpose.
Add styles for articles list.
=> refactor: update chapter template

source/reference/stable/order-api/get-orders.md, source/reference/stable/order-api/get-shipments.md
https://centracommerce.atlassian.net/browse/CCT-630
=> CCT-630: Add orderApi docs

user/themes/centra/scss/_content.scss
Style ordered list to use for steps
=> fix: Add ordered list styles

user/config/system.yaml, user/themes/centra/scss/_toc.scss
=> fix: Make Page navigation bigger and add scroll

user/pages/03.guides/01.fe-development/docs.md, user/pages/04.api-references/01.store-api/docs.md
=> Symek's docs edits

user/pages/03.guides/01.fe-development/docs.md, user/pages/04.api-references/01.store-api/docs.md
Reverts centrahq/api-documentation#103
=> Revert "Symek's docs edits"

user/themes/centra/scss/_content.scss, user/themes/centra/templates/chapter.html.twig, user/themes/centra/templates/partials/content.html.twig
Fixes [JIRA](https://centracommerce.atlassian.net/browse/SHOWROOM-513)
=> fix: chapter header (SHOWROOM-513)

user/themes/centra/scss/_content.scss, user/themes/centra/templates/chapter.html.twig
Fixes [JIRA](https://centracommerce.atlassian.net/browse/SHOWROOM-514)
=> fix: add link to article title (SHOWROOM-514)

user/themes/centra/scss/_content.scss, user/themes/centra/scss/_sidebar.scss
Fixes [JIRA](https://centracommerce.atlassian.net/browse/SHOWROOM-515)
=> fix: horizontal scroll and jumping menu (SHOWROOM-515)

source/reference/stable/order-api/update-return.md, source/theme/sidebar-reference-old.html
- add documentation that describes Order API update return
- update documentation for Order API get returns
=> Update Return documentation

source/reference/stable/subscription-api/get-subscriptions.md, source/reference/stable/subscription-api/register-payment.md, source/reference/stable/subscription-api/update-subscription.md, source/theme/sidebar-reference-old.html
[Task](https://centracommerce.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=CCT-1593&sprint=99)
[PR](https://github.com/centrahq/silk/pull/4869)
Stage: on RC
=> Update subscription api

source/reference/stable/order-api/create-voucher.md, source/reference/stable/order-api/get-voucher.md, source/theme/sidebar-reference-old.html
[Task](https://centracommerce.atlassian.net/browse/CCT-1584)
[PR](https://github.com/centrahq/silk/pull/5006)
=> add GET POST voucher endpoints

source/reference/stable/order-api/create-voucher.md, source/reference/stable/subscription-api/get-subscription.md, source/reference/stable/subscription-api/get-subscriptions.md, source/reference/stable/subscription-api/register-payment.md, source/reference/stable/subscription-api/update-subscription.md, source/theme/sidebar-reference-old.html
[Task](https://centracommerce.atlassian.net/browse/CCT-1642)
[PR](https://github.com/centrahq/silk/pull/4996)
New get subscription endpoint.
New pricelist, packages and customer field in subscription response body
=> Get subscription endpoint

source/reference/stable/subscription-api/register-payment.md
https://github.com/centrahq/silk/pull/5086
=> CCT-1804 Add receipt to Register Payment endpoint

source/reference/stable/order-api/clone-voucher.md, source/reference/stable/order-api/create-voucher.md
Removed code validation errors
=> Update voucher documentation

source/guides/plugins/mailchimp-ecommerce.md
Added docs about mailchimp tags
=> Added docs about mailchimp tags

source/reference/stable/order-api/create-voucher.md, source/reference/stable/order-api/get-voucher.md
=> Add freeShipping info to Order API vouchers endpoints

source/guides/plugins/adyen-drop-in.md
I also wonder if a complete example would be a good idea.
The documentation makes it feel like a more complicated task than it really is.
=> See the individual commits for more information

pages/06.plugins/02.stripe-payment-intents/docs.md, pages/06.plugins/06.adyen-drop-in/docs.md
Fixes https://centracommerce.atlassian.net/browse/WHOLESALE-1945
=> fix: Add table wrapper

pages/05.api-references/05.graphql-integration-api/05.media-upload/docs.md
Was reviewed here but it was pointing to master branch.
https://github.com/centrahq/api-documentation/pull/181
=> Integration API: Product Media upload documentation

buildpack-run.sh, config/plugins/highlight.yaml
[Jira](https://centracommerce.atlassian.net/browse/WHOLESALE-2029)
Grav plugin `highlight` is not compatible with pjax logic
=> refactor: drop highlight plugin

config/site.yaml
[Jira](https://centracommerce.atlassian.net/jira/software/projects/WHOLESALE/boards/12?selectedIssue=WHOLESALE-2043)
=> feat: add google target id for analytics

composer.json
https://devcenter.heroku.com/articles/php-support#available-versions
=> fix: update php version

config/site.yaml
[Jira](https://centracommerce.atlassian.net/jira/software/projects/WHOLESALE/boards/12?selectedIssue=WHOLESALE-2049)
=> feat: add hotgar tracking id

pages/01.overview/08.custom-attributes/docs.md, pages/05.api-references/02.checkout-api/02.order-flow/docs.md
[Jira](https://centracommerce.atlassian.net/jira/software/projects/WHOLESALE/boards/12?selectedIssue=WHOLESALE-2040)
=> refactor: remove usage of snippet shortcodes

pages/06.plugins/13.qliroone/docs.md
After supporting madepeople in integrating Qliro, I noticed that some information could be clarified to prevent more misalignments in the future with other people
=> update information about qliro payment widget handling in the checkout

config/plugins/page-toc.yaml
https://github.com/trilbymedia/grav-plugin-page-toc#configuration
=> Specify max length for slugs

buildpack-run.sh, config/plugins/svg-extension.yaml
Added SVG extension plugin to be able to use SVG files in twig templates
=> Add svg extension plugin

pages/01.overview/06.taxes/docs.md, pages/05.api-references/04.order-api/01.api-reference/101.create-order/docs.md
Delete duplicated param and add `shippingList` description.
=> Order API docs updates

pages/06.plugins/12.external-payment-plugin/docs.md
https://centracommerce.atlassian.net/browse/SBMR-306
=> SBMR-306 external payment plugin docs improvements

pages/01.overview/08.custom-attributes/docs.md
[Documentation section with custom attributes](https://docs.centra.com/overview/custom-attributes#api-output)
Added example config of product media attribute with responses from both Checkout and Shop API
=> DTCT-352 product media attributes

app.json, composer.json, composer.lock
- Upgrade heroku stack `18` -> `22`
- Upgrade php version `7.3.24` -> `8.1.8`
=> chore: upgrade stack

app.json, buildpack-run.sh, pages/graphql-explorer/graphql-explorer.md
[Jira](https://centracommerce.atlassian.net/browse/WHOLESALE-2867)
- Added `/graphql-exlporer` page
- Move themes repository URL to env variables
=> add graphql-explorer page

pages/03.fe-development/01.fe-elements/docs.md, pages/03.fe-development/03.launch-checklist/docs.md, pages/05.api-references/02.checkout-api/02.api-reference/03.selections-and-orders/docs.md, pages/05.api-references/02.checkout-api/03.order-flow/docs.md
Remove all plugins mentions, related to this ticket:
https://centracommerce.atlassian.net/browse/CORE-200
=> CORE-200: Remove all deleted plugins mentions from documentation

pages/03.fe-development/11.backinstock/docs.md
[DTCT-502](https://centracommerce.atlassian.net/browse/DTCT-502)
=> DTCT-502: Add some information about why we still allow product in newsletter-subscription endpoint

pages/03.fe-development/12.lowestprice/docs.md
https://centracommerce.atlassian.net/browse/DTCT-477
=> [DTCT-477] External documentation

pages/06.plugins/15.klaviyo/docs.md
https://centracommerce.atlassian.net/browse/KI-105
=> KI-105: Remove beta label

pages/06.plugins/15.klaviyo/docs.md
https://centracommerce.atlassian.net/browse/KI-100
=> KI-100: Add information about extra ingrid data (to merge with task)

pages/06.plugins/15.klaviyo/docs.md
https://centracommerce.atlassian.net/browse/KI-102
=> KI-102: Add extra fields for Shipping Update (to merge with task)

pages/06.plugins/15.klaviyo/docs.md
https://centracommerce.atlassian.net/browse/KI-114
=> KI-114: Update shipping fields

pages/06.plugins/15.klaviyo/docs.md
https://centracommerce.atlassian.net/browse/KI-118
=> KI-118: Add back in stock information with example

pages/03.fe-development/01.fe-elements/docs.md, pages/05.api-references/02.checkout-api/01.introduction/docs.md
[DTCT-607: Ensure Checkout API docs clearly mentions the API is to be cached](https://centracommerce.atlassian.net/browse/DTCT-607)
=> DTCT-607: Ensure Checkout API docs clearly mentions the API is to be cached

pages/03.fe-development/11.backinstock/docs.md
[Task] https://centracommerce.atlassian.net/browse/DTCT-488
Explain how the old solution works and link to the new one. Swagger documentation was updated in parallel ->  https://github.com/centrahq/silk/pull/11492.
=> DTCT-488: Back in stock old newsletter info update (merge with DTC task)

pages/06.plugins/05.adyen/docs.md, pages/06.plugins/06.adyen-drop-in/docs.md
Added warning to set the corresponding notification URL for multiple plugins
=> [SBFT-1224] Added warning about multiple plugins

pages/05.api-references/05.graphql-integration-api/05.media-upload/docs.md
Updated some documentation on Media batch upload via GQL
=> Update media batch upload

pages/06.plugins/15.klaviyo/docs.md
Better examples for back in stock emails
=> klaviyo back in stock emails - better data reference/snippets

pages/03.fe-development/11.backinstock/docs.md
Added more explanations about the back in stock
=> Added more information about old vs new back in stock notifications

config/site.yaml
- Added piwikPROContainerID to site config
Related with https://github.com/centrahq/centra-grav-themes/pull/84
=> chore: piwikPRO containerId added

pages/05.api-references/02.checkout-api/02.api-reference/03.selections-and-orders/docs.md
[DTCT-705](https://centracommerce.atlassian.net/browse/DTCT-705)
[DTCT-705]: https://centracommerce.atlassian.net/browse/DTCT-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DTCT-705] Docs for modifying selection in one request

pages/03.fe-development/08.ingrid-implementation/docs.md, pages/03.fe-development/09.ingridv2-implementation/docs.md
https://centracommerce.atlassian.net/browse/DTCT-910
=> [DTCT-910] Update IngridV2/V1 docs

pages/04.guides/03.pim-gql-integration/docs.md, pages/05.api-references/05.graphql-integration-api/chapter.md
=> INT-1000: Marked GraphQL as stable, not a Beta anymore

pages/04.guides/01.cms-integration/docs.md, pages/04.guides/02.erp-integration/docs.md, pages/05.api-references/01.api-intro/01.api-functions/docs.md, pages/05.api-references/07.soap-integration-api/01.api-reference/docs.md, pages/05.api-references/07.soap-integration-api/chapter.md
Added some deprecation notices.
=> INT-1000: Marked SOAP as deprecated

pages/04.guides/07.erp-gql-integration/docs.md
=> Added an ERP guide using GQL

pages/04.guides/01.cms-integration/docs.md, pages/04.guides/02.erp-integration/docs.md, pages/05.api-references/01.api-intro/01.api-functions/docs.md, pages/05.api-references/07.soap-integration-api/01.api-reference/docs.md, pages/05.api-references/07.soap-integration-api/chapter.md
This reverts commit aa06d226b0ea3097bfd5d1eea49a59e3e9be13e3.
=> Revert "Marked SOAP as deprecated"

pages/01.overview/08.custom-attributes/docs.md
documentations for voucher custom attribute type
https://centracommerce.atlassian.net/browse/CORE-1434
=> CORE-1434: documentations

pages/03.fe-development/12.backinstock/docs.md, pages/04.guides/02.erp-gql-integration/docs.md, pages/05.api-references/01.api-intro/01.api-functions/docs.md
DTCT-1058 graphql cancel order
=> DTCT-1058 graphql cancel order

pages/05.api-references/05.graphql-integration-api/05.examples/01.dtc/docs.md
specs here: 
https://centracommerce.atlassian.net/wiki/spaces/IGQL/pages/562662918/Release+remaining+authorization+specification
=> DTCT-1064 Add GQL docs for releaseRemainingOrderAuthorizaiton mutation

pages/05.api-references/05.graphql-integration-api/01.authorization/docs.md
Release remaining order authorization mutation in GQL
=> Release remaining order authorization mutation in GQL

pages/06.plugins/06.adyen-drop-in/docs.md, pages/06.plugins/15.klaviyo/docs.md
add section about apple pay, google pay and paypal configuration #585
=> add section about apple pay, google pay and paypal configuration #585

pages/06.plugins/15.klaviyo/docs.md
We have issue with catalog synchronization for Klaviyo. In the new version, the localized version of the product URL can be obtained through metadata.ProductUrls
=> DTCT-1013 ProductURLs for Klaviyo

pages/05.api-references/02.graphql-integration-api/03.api-rate-limits/docs.md
[task](https://centracommerce.atlassian.net/browse/INT-1241?atlOrigin=eyJpIjoiNGQ0ZTI2MTA1MDgzNGRlNmI3NGMyN2E2OWUxMzhlMWIiLCJwIjoiaiJ9)
=> INT-1241: get rid of expand panel

pages/04.guides/07.pos-integration/docs.md, pages/05.api-references/06.order-api/02.api-reference/113.update-allocation-request/docs.md, pages/05.api-references/06.order-api/02.api-reference/114.get-allocation-requests/docs.md
JIRA: https://centracommerce.atlassian.net/browse/CORE-2389
Silk PR: https://github.com/centrahq/silk/pull/14248
=> CORE-2389: Order API allocation-requests docs updated

pages/04.guides/07.pos-integration/docs.md, pages/05.api-references/06.order-api/02.api-reference/104.get-orders/docs.md, pages/05.api-references/06.order-api/02.api-reference/113.update-allocation-request/docs.md, pages/05.api-references/06.order-api/02.api-reference/114.get-allocation-requests/docs.md
=> Publish the new Order API docs

config/site.yaml
https://github.com/centrahq/api-documentation/pull/672 -> prod
=> subscriptions redirect fix -> prod
